services:
  - type: web
    name: Api
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    branch: main
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        value: "Host=ep-shy-fog-a9mzxt8k-pooler.gwc.azure.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_ImDzG2WxK6Ue;SSL Mode=Require;Trust Server Certificate=true;"
    healthCheckPath: /
    startCommand: "dotnet Api.dll"
